export const sample_foods = [
  {
    id: '1',
    name: 'Dal Makhani',
    cookTime: '30',
    price: 150,
    favorite: true,
    origins: ['Punjab'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['Protein', 'Lunch'],
  },
  {
    id: '2',
    name: 'Rajasthani Thali',
    price: 80,
    cookTime: '40',
    favorite: false,
    origins: ['rajasthan'],
    stars: 5,
    imageUrl: 'food-2.jpg',
    tags: ['FullMeal', 'Lunch', 'Dinner'],
  },
  {
    id: '3',
    name: 'Gulab Jamun',
    price: 5,
    cookTime: '10-15',
    favorite: true,
    origins: ['Punjab'],
    stars: 4,
    imageUrl: 'food-4.jpg',
    tags: ['SweetDish', 'Tasty'],
  },
  {
    id: '4',
    name: 'Raj Kachodi',
    price: 50,
    cookTime: '15-20',
    favorite: true,
    origins: ['Rajasthan'],
    stars: 3.5,
    imageUrl: 'food-6.jpg',
    tags: ['Snack', 'Tasty'],
  },
  {
    id: '5',
    name: 'Gujarati Thali',
    price: 200,
    cookTime: '40-50',
    favorite: false,
    origins: ['Gujarat'],
    stars: 3.5,
    imageUrl: 'food-3.jpg',
    tags: ['FullMeal', 'Lunch','Dinner'],
  },
  {
    id: '6',
    name: 'Malai Ghevar',
    price: 200,
    cookTime: '120',
    favorite: false,
    origins: ['rajasthan'],
    stars: 4.0,
    imageUrl: 'food-5.jpg',
    tags: ['Tasty', 'SweetDish', 'Breakfast'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'Tasty', count: 4 },
  { name: 'SweetDish', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'Breakfast', count: 2 },
  { name: 'FullMeal', count: 1 },
  { name: 'Protein', count: 1 },
  { name: 'Dinner', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];
